### PR TITLE
Support for workspace settings

### PR DESCRIPTION
**Pull request by codeunifier**
This isn't fully fleshed out, but it's got basic workspace setting support (didn't do extensions, but I'd imagine it could be set up in a similar fashion).

I didn't add any support for automatically adding settings to the workspace json, but if users manually add settings this should adhere to them when switching profiles.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Just so I can understand, is the objective here to have is so you could open a workspace and have a specific profile loaded?

**Comment by codeunifier** [comment]
With my particular setup for work, I have several projects where I have a different workspace for the frontend and the backend, and I'll have one window open with the backend and one open with the frontend. So this would allow someone like me to be able to have more generalized profiles with more specific settings in the workspace. Without this support, workspace settings get ignored when switching profiles.

Granted, I feel like my setup probably isn't the norm for most people, so if this doesn't make the cut that's totally understandable.

**Comment by aaronpowell** [comment]
No, I have thought there could be value in being able to apply the settings on a single workspace.

Originally, the extension was created for when I was presenting, and then I'd want all VS Code instances the same, but then it became useful for scenarios like you described, but not designed for it.

**Comment by richarddavenport** [comment]
> No, I have thought there could be value in being able to apply the settings on a single workspace.
> 
> Originally, the extension was created for when I was presenting, and then I'd want all VS Code instances the same, but then it became useful for scenarios like you described, but not designed for it.

@aaronpowell Are you open to adjusting the design so it could handle this type of scenario?

**Comment by aaronpowell** [comment]
> > No, I have thought there could be value in being able to apply the settings on a single workspace.
> > Originally, the extension was created for when I was presenting, and then I'd want all VS Code instances the same, but then it became useful for scenarios like you described, but not designed for it.
> 
> @aaronpowell Are you open to adjusting the design so it could handle this type of scenario?

Sure, I just want to make sure that there's an understandable way to set the usage correctly. As I mentioned my usage is to apply it for all instances when presenting, so I'd want to make sure that that is still possible in addition to workspace support.

**Comment by hurrycaner** [comment]
I want to use it as well, how can i help?

**Comment by gusbemacbe** [comment]
@codeunifier, @richarddavenport and @hurrycaner 

It appears that @aaronpowell's extension is multiroot workspace-compatible. Here is the screenshot:

image

image

**Comment by aaronpowell** [comment]
I'm going through the process of depricating this extension as the VS Code team is working on bringing this as a first-party supported feature, see https://code.visualstudio.com/updates/v1_69#_settings-profiles

**Pull request closed without merging**
